[packages]
"iwd",
"yay",
"pipewire",
"pipewire-pulse",
"rofi",
"rofimoji",
"picom",
"wezterm",
"zsh",
"fasfetch",
"oh-my-posh",
"nautilus",
"playerctl",
"bat",
"eza",
"zoxide",
"pacman-contrib",
"clipcat",
"cava",
"maim",
"libnotify",
"stow",
"neovim",


[fonts]
"noto-fonts",
"noto-fonts-cjk",
"noto-fonts-emoji",
"dm-sans",
"jebrains-mono",
"icomoon-feather",
"nerd-font-symbols",
